name: open_library
description: A flutter package to consume the openlibrary.org api in a simple way
version: 0.1.5
homepage: https://gitlab.com/alange/open_library
documentation: https://gitlab.com/alange/open_library
repository: https://gitlab.com/alange/open_library

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  chopper: ^4.0.4
  equatable: ^2.0.3
  json_annotation: ^4.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  chopper_generator: ^4.0.3
  json_serializable: ^6.1.3

  build_runner:

flutter:


