name: open_library_api
description: A flutter package to consume the openlibrary.org api in a simple way
version: 0.1.6
homepage: https://github.com/Pastajello/open_library-main
documentation: https://github.com/Pastajello/open_library-main
repository: https://github.com/Pastajello/open_library-main

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  chopper: ^4.0.4
  equatable: ^2.0.3
  json_annotation: ^4.4.0


dev_dependencies:
  chopper_generator: ^4.0.3
  json_serializable: ^6.1.3
  test: ^1.16.0
  build_runner: